/**
 * Themes shared by github-readme-stats, the streak service, and repo pins.
 *
 * A union rather than `string` so that adding a theme to the picker and adding
 * it to the type are the same edit — the config file is typed against this, so
 * a slug that does not exist upstream cannot quietly reach a card URL.
 */
export type StatsTheme
  = | 'default'
    | 'transparent'
    | 'dark'
    | 'radical'
    | 'merko'
    | 'gruvbox'
    | 'gruvbox_light'
    | 'tokyonight'
    | 'onedark'
    | 'cobalt'
    | 'cobalt2'
    | 'synthwave'
    | 'highcontrast'
    | 'dracula'
    | 'prussian'
    | 'monokai'
    | 'vue'
    | 'vue-dark'
    | 'shades-of-purple'
    | 'nightowl'
    | 'buefy'
    | 'blue-green'
    | 'algolia'
    | 'great-gatsby'
    | 'darcula'
    | 'bear'
    | 'solarized-dark'
    | 'solarized-light'
    | 'chartreuse-dark'
    | 'nord'
    | 'gotham'
    | 'material-palenight'
    | 'graywhite'
    | 'vision-friendly-dark'
    | 'ayu-mirage'
    | 'midnight-purple'
    | 'calm'
    | 'calm_pink'
    | 'flag-india'
    | 'omni'
    | 'react'
    | 'jolly'
    | 'maroongold'
    | 'yeblu'
    | 'blueberry'
    | 'slateorange'
    | 'kacho_ga'
    | 'outrun'
    | 'ocean_dark'
    | 'city_lights'
    | 'github_dark'
    | 'github_dark_dimmed'
    | 'discord_old_blurple'
    | 'aura'
    | 'aura_dark'
    | 'panda'
    | 'noctis_minimus'
    | 'swift'
    | 'apprentice'
    | 'moltack'
    | 'codeSTACKr'
    | 'rose_pine'
    | 'rose'
    | 'date_night'
    | 'one_dark_pro'
    | 'holi'
    | 'neon'
    | 'blue_navy'
    | 'catppuccin_latte'
    | 'catppuccin_mocha'
    | 'ambient_gradient'
    | 'shadow_blue'
    | 'shadow_green'
    | 'shadow_red'

/** Layouts the top-languages card can be drawn in. */
export type LangLayout = 'compact' | 'normal' | 'donut' | 'donut-vertical' | 'pie'

/** Themes understood by github-profile-trophy — its own set, not the stats one. */
export type TrophyTheme
  = | 'default'
    | 'aura'
    | 'flat'
    | 'onedark'
    | 'gruvbox'
    | 'dracula'
    | 'monokai'
    | 'chalk'
    | 'nord'
    | 'alduin'
    | 'darkhub'
    | 'juicyfresh'
    | 'buddhism'
    | 'oldie'
    | 'radical'
    | 'onestar'
    | 'discord'
    | 'algolia'
    | 'gitdimmed'
    | 'tokyonight'
    | 'matrix'
    | 'apprentice'
    | 'dark_dimmed'
    | 'dark_lover'
    | 'kimbie_dark'

/**
 * Trophy categories the card can be filtered down to. These are the upstream
 * `title` values verbatim — `MultiLanguage`, not `MultipleLang` — because the
 * service silently ignores a filter it does not recognise and returns every
 * trophy instead of erroring.
 */
export type TrophyTitle
  = | 'Stars'
    | 'Commits'
    | 'Followers'
    | 'Issues'
    | 'PullRequest'
    | 'Repositories'
    | 'Reviews'
    | 'Experience'
    | 'MultiLanguage'
    | 'LongTimeUser'
    | 'AncientUser'
    | 'OGUser'
    | 'Organizations'
    | 'Joined2020'
    | 'AllSuperRank'

/** Themes understood by github-readme-activity-graph — again its own set. */
export type ActivityTheme
  = | 'github'
    | 'github-light'
    | 'github-dark'
    | 'github-dark-dimmed'
    | 'github-compact'
    | 'react'
    | 'react-dark'
    | 'vue'
    | 'xcode'
    | 'rogue'
    | 'nord'
    | 'gotham'
    | 'high-contrast'
    | 'dracula'
    | 'merko'
    | 'gruvbox'
    | 'monokai'
    | 'nightowl'
    | 'noctis-minimus'
    | 'tokyo-night'
    | 'tokyo-day'
    | 'radical'
    | 'redical'
    | 'chartreuse-dark'
    | 'material'
    | 'material-palenight'
    | 'one-dark'
    | 'cobalt'
    | 'synthwave-84'
    | 'minimal'
    | 'modern-lilac'
    | 'elegant'
    | 'lucent'
    | 'arctic'
    | 'aqua'
    | 'coral'
    | 'green'
